services:
  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite://./db.sqlite
    env_file:
      - .env
    volumes:
      - ./db.sqlite:/app/db.sqlite
